CREATE TABLE IF NOT EXISTS slots (  
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    time TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS appointments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    slot_id INTEGER NOT NULL,
    FOREIGN KEY (slot_id) REFERENCES slots(id)
);
